
/** 自定义初始化信息 */
export const DEFINE_MESSAGE = {
  /** 定义的是打印格式化输出数组的唯一标识id, 用于区分正常打印和自定义打印 */
  PRINTER_MESSAGE_ARR_FLAG: '__suey_printer_process_id__',

  PRINTER_MESSAGE_CLEAR_FLAG: 'PRINTER_MESSAGE_CLEAR_FLAG',

  PRINTER_MESSAGE_ANSI_STYLE_FLAG: 'PRINTER_MESSAGE_ANSI_STYLE_FLAG',
  PRINTER_MESSAGE_CSS_STYLE_FLAG: 'PRINTER_MESSAGE_CSS_STYLE_FLAG'
} as const;
